export const cards = [
  'El Loco',
  'El Mago',
  'La Sacerdotisa',
  'La Emperatriz',
  'El Emperador',
  'El Hierofante',
  'Los Amantes',
  'El Carro',
  'Justicia',
  'El Ermitano',
  'Rueda de la Fortuna',
  'Fuerza',
  'El Colgado',
  'Muerte',
  'Templanza',
  'El Diablo',
  'La Torre',
  'La Estrella',
  'La Luna',
  'El Sol',
  'Juicio',
  'El Mundo',
  'As de Bastos',
  'Dos de Bastos',
  'Tres de Bastos',
  'Cuatro de Bastos',
  'Cinco de Bastos',
  'Seis de Bastos',
  'Siete de Bastos',
  'Ocho de Bastos',
  'Nueve de Bastos',
  'Diez de Bastos',
  'Sota de Bastos',
  'Caballero de Bastos',
  'Reina de Bastos',
  'Rey de Bastos',
  'As de Copas',
  'Dos de Copas',
  'Tres de Copas',
  'Cuatro de Copas',
  'Cinco de Copas',
  'Seis de Copas',
  'Siete de Copas',
  'Ocho de Copas',
  'Nueve de Copas',
  'Diez de Copas',
  'Sota de Copas',
  'Caballero de Copas',
  'Reina de Copas',
  'Rey de Copas',
  'As de Oros',
  'Dos de Oros',
  'Tres de Oros',
  'Cuatro de Oros',
  'Cinco de Oros',
  'Seis de Oros',
  'Siete de Oros',
  'Ocho de Oros',
  'Nueve de Oros',
  'Diez de Oros',
  'Sota de Oros',
  'Caballero de Oros',
  'Reina de Oros',
  'Rey de Oros',
];
